### ISSUE TITLE
Component Question: Importing/Using React.js Components

### ISSUE THREAD

**Issue by IvanDrag0** [Badgerati/Pode.Web#142]
I know that the framework uses template and components based on Bootstrap, jQuery, Material Design Icons, Chart.js, and Highlight.js frameworks.  However, is it possible to integrate (even if it's manually) some React.js components? I'm interested in the types of components found in this repo:

[https://github.com/EasyDynamics/oscal-react-library](https://github.com/EasyDynamics/oscal-react-library)

**Comment by Badgerati** [comment]
It's do-able but difficult with the way the rest of the module works. I briefly looked when we were looking at switching the icon pack before settling on MDI, and due to the way React works it didn't properly work with the way Pode.Web's built.

A few people have asked about React now though, and I just need to work on getting the time to learn it properly and see if I can overhaul Pode.Web to use React instead - or even in conjunction with Bootstrap.

If it's only small independent components you want, you can import React/Babel manually, and reference a custom javascript file to be used via `Import-PodeWebJavascript`. Then build a REST API via `Add-PodeRoute` to get the data for the components that way :)
