### ISSUE TITLE
Use custom template

### ISSUE THREAD

**Issue by breento** [Badgerati/Pode.Web#188]
Hey @Badgerati ,

Is it somehow possible to use a custom Template view instead of the one in Pode.Web\version\Template\Views directory? That way I can for example remove the Sign out button in the right area of the top nav bar.

**Comment by Badgerati** [comment]
Hey @breento,

Unfortunately it isn't, mostly due to all the dynamic PowerShell Pode.Web embeds into its view files.

You can however use custom CSS/JS to control how the page looks, [see here](https://badgerati.github.io/Pode.Web/Tutorials/ClassAndStyles/).

This means you could have a file at `/public/style.css` with the following content:
```css
form[action='/logout'] button {
    display: none;
}
```

and using `Import-PodeWebStylesheet -Url '/style.css'`, this should hide the "Sign Out" button.

**Comment by breento** [comment]
Thanks! That's working great!
By the way great work with Pode.Web!

**Comment by Clifra-Jones** [comment]
@Badgerati thank you, your reply here got me out of a stuck situation. Twice I've been tripped up by paths that are relative to the public folder.
