### ISSUE TITLE
Log All Errors to Toasts

### ISSUE THREAD

**Issue by fatherofinvention** [Badgerati/Pode.Web#403]
### Question
I am trying to redirect or log all errors to the screen from a file or terminal. I thought a custom logging method would be the best way to do this but I can't get it working. Is this possible?

```powershell
   $method = New-PodeLoggingMethod -Custom -ScriptBlock {
      param($item)
     Show-PodeWebToast -Message "$($item.Server) - $($item.Message)" -Duration 10000
  }
  
  $method | Enable-PodeErrorLogging -Raw
```

**Comment by ili101** [comment]
I don't think it is possible correctly?
Errors from the same session i use "try catch".
From a file you can use `New-PodeWebFileStream`.

**Comment by fatherofinvention** [comment]
Thanks. My goal is to surface errors to the relevant page and not have a file stream on every page. I wonder what the current limitation is that makes it not possible to use toasts for this?

@Badgerati do you think this is something that could be implemented in the future?

**Comment by Badgerati** [comment]
Hey @fatherofinvention,

It's not possible due to how logging works. `Show-PodeWebToast` requires a `$WebEvent` to be available, but logging is done outside of the Request\`$WebEvent` scope - so the hashtable it returns just goes into the ether 😄 

To redirect the errors to Toasts would likely require some rework in Pode as well 🤔. The errors shown as Toasts on the page though would only be errors for the current user on that page; errors from elsewhere, like Schedules/Tasks or other users on the same page, wouldn't appear - to do this would require websocket support, which is on the roadmap!

The former does sound like what you're after: error logs for a user on the current page as Toasts?

**Comment by fatherofinvention** [comment]
Hey @Badgerati , you’ve got it exactly right. I’ll look at doing this again when web socket support is ready. Thanks for the insight!
