### ISSUE TITLE
Add Support for Material-UI Icons set and possiblely other icons sets

### ISSUE THREAD

**Issue by the-mentor** [Badgerati/Pode.Web#73]
The current Feather Icons is missing a lot of icons for things like Telegram and many more 

https://material-ui.com/components/material-icons/

Examples:
MaterialUI Icons: 
![image](https://user-images.githubusercontent.com/11185446/121191916-17be2c00-c875-11eb-925f-4b50f61ed8a8.png)

Feather Icons:
![image](https://user-images.githubusercontent.com/11185446/121191999-2c9abf80-c875-11eb-80e5-dc7959058200.png)

**Comment by Badgerati** [comment]
It looks like Material UI sadly has a dependency on React 😕 

I've been considering changing the icons to https://icons.getbootstrap.com actually, which also has vastly more than feather; does this one also have the ones you're looking for? (I can see Telegram in there)

**Comment by the-mentor** [comment]
@Badgerati from what I can tell material ui is built on react but the icons themselves do not require the whole material ui.

Also they look much better then the other icons sets in my personal opinion.

Here is a direct link to the icon pack if it helps. 

https://www.npmjs.com/package/@material-ui/icons

**Comment by Badgerati** [comment]
@the-mentor I was hoping the same, but when I looked at the files in the icon pack they're all nodejs/react js files: https://yarnpkg.com/package/@material-ui/icons?files, rather than pure svgs.

I'll dig a little to see if anyone's managed it, but so far everything I've found says it's just for React 😕

**Comment by the-mentor** [comment]
> 
> 
> @the-mentor I was hoping the same, but when I looked at the files in the icon pack they're all nodejs/react js files: https://yarnpkg.com/package/@material-ui/icons?files, rather than pure svgs.
> 

What a huge bummer !!
I wonder if its somehow possible to convert them to pure svgs so we can use them in this project.

@ili101  maybe you have any smart ideas ?

**Comment by ili101** [comment]
https://icons.getbootstrap.com/ have more variety then what we have now.

It looks like material-ui/icons is some sort of library for React that generates svg files on the fly with required size, color, team, etc https://material-ui.com/components/icons/#svg-material-icons.
In the description of this library it's mentioned that the icons are taken from https://fonts.google.com/icons but there is no "Telegram" icon in there, maybe a trademark issue or the fact that this is Google so it doesn't help us.
The only thing I can think of is when building to install React and this, dump all the icons somehow to svg and include them. but this feels like a workaround, don't know if this is something we will like to persuade. @Badgerati?
I think it's going back to https://github.com/Badgerati/Pode.Web/issues/1 Bootstrap vs React, and if we like to include React with its benefits but also its overhead and extra complexity (in this project or a fork of it?).

**Comment by Badgerati** [comment]
> The only thing I can think of is when building to install React and this, dump all the icons somehow to svg and include them.

I did have this thought as well, this morning, but it does feel far to hacky.

Looking at the package again, it appears it's React, Babel, and core Material UI that it has a dependency on - so not just the icons. I would prefer to not add in the overhead of React just for icons - for now. The bootstrap ones give us ~5x more icons than feather, and should be a lot quicker to implement into Pode.Web at the moment 😛 

I have taken a look at React here and there, to see where/how it might fit in to Pode.Web, but its JSX format it making it hard to find a decent way of doing it 🤔 (because of the way layouts/elements are generated, it could be building the same thing twice. Or, we dynamically build the JSX like the views, but then it means having Babel running on the client-side - which is dirty). Then again, I've also only investigated it a bit.

**Comment by the-mentor** [comment]
@Badgerati not icon related but this seems to be a really nice Material theme that is only based on CSS and JS rather then react which can be an interesting idea to implement.

https://github.com/materializecss/materialize

**Comment by the-mentor** [comment]
@Badgerati I also found this:

It looks like Home Assistant another open source project uses these material icons it looks like its a webfont that also includes SVGs so its totally worth checking out!

https://materialdesignicons.com/

![image](https://user-images.githubusercontent.com/11185446/121559919-b25a6e80-ca1f-11eb-8fa0-270f8fdcd9d4.png)

**Comment by Badgerati** [comment]
@the-mentor I saw the material design icons the other night, but didn't mention it and they didn't have a telegram icon 😄 They do look cool though!

**Comment by Badgerati** [comment]
So they do!! Well then, if we're good with those icons I'll see if I can get them in 😄

**Comment by Badgerati** [comment]
That commit contains a switch over to material design icons. They do look nicer, and easier to use than feather, too :)
